# Navarch configuration
#
# This file demonstrates configuration with single-provider and multi-provider pools.
# Resources are separated by --- and each has apiVersion, kind, metadata, and spec.

# Control plane configuration
apiVersion: navarch.io/v1alpha1
kind: ControlPlane
metadata:
  name: production
  labels:
    environment: production
spec:
  address: ":50051"
  healthCheckInterval: 60s
  heartbeatInterval: 30s
  enabledHealthChecks:
    - boot
    - nvml
    - xid
  autoscaleInterval: 30s

---
# Lambda Labs provider
apiVersion: navarch.io/v1alpha1
kind: Provider
metadata:
  name: lambda
  labels:
    cloud: lambda
spec:
  type: lambda
  lambda:
    apiKeyEnvVar: LAMBDA_API_KEY

---
# GCP provider
apiVersion: navarch.io/v1alpha1
kind: Provider
metadata:
  name: gcp
  labels:
    cloud: gcp
spec:
  type: gcp
  gcp:
    project: my-gcp-project

---
# Fake provider for development
apiVersion: navarch.io/v1alpha1
kind: Provider
metadata:
  name: fake
  labels:
    cloud: fake
spec:
  type: fake
  fake:
    gpuCount: 8

---
# Multi-provider pool: fungible compute across Lambda and GCP
# Uses priority strategy: tries Lambda first, falls back to GCP if unavailable
apiVersion: navarch.io/v1alpha1
kind: Pool
metadata:
  name: fungible
  labels:
    workload: training
    tier: premium
spec:
  providers:
    - name: lambda
      priority: 1
      regions: [us-west-2, us-east-1]
    - name: gcp
      priority: 2
      regions: [us-central1]
      instanceType: a3-highgpu-8g  # Override for GCP-specific type
  providerStrategy: priority
  instanceType: h100-8x  # Abstract type, mapped to provider-specific types
  scaling:
    minReplicas: 4
    maxReplicas: 32
    cooldownPeriod: 5m
    autoscaler:
      type: reactive
      scaleUpThreshold: 75
      scaleDownThreshold: 25
  health:
    unhealthyThreshold: 2
    autoReplace: true

---
# Cost-optimized multi-provider pool: always picks cheapest option
apiVersion: navarch.io/v1alpha1
kind: Pool
metadata:
  name: cost-optimized
  labels:
    workload: batch
    tier: economy
spec:
  providers:
    - name: lambda
    - name: gcp
  providerStrategy: cost
  instanceType: a100-8x
  scaling:
    minReplicas: 0
    maxReplicas: 100
    cooldownPeriod: 3m
    autoscaler:
      type: queue
      jobsPerNode: 10
  health:
    unhealthyThreshold: 3
    autoReplace: true

---
# Training pool with reactive autoscaling (single provider)
apiVersion: navarch.io/v1alpha1
kind: Pool
metadata:
  name: training
  labels:
    workload: training
    tier: standard
spec:
  providerRef: lambda
  instanceType: gpu_8x_h100_sxm5
  region: us-west-2
  sshKeyNames:
    - ops-team
    - ml-team
  labels:
    workload: training
  scaling:
    minReplicas: 2
    maxReplicas: 20
    cooldownPeriod: 5m
    autoscaler:
      type: reactive
      scaleUpThreshold: 80
      scaleDownThreshold: 20
  health:
    unhealthyThreshold: 2
    autoReplace: true

---
# Inference pool with queue-based autoscaling
apiVersion: navarch.io/v1alpha1
kind: Pool
metadata:
  name: inference
  labels:
    workload: inference
    tier: standard
spec:
  providerRef: lambda
  instanceType: gpu_1x_a100_sxm4
  region: us-east-1
  scaling:
    minReplicas: 4
    maxReplicas: 50
    cooldownPeriod: 2m
    autoscaler:
      type: queue
      jobsPerNode: 100
  health:
    unhealthyThreshold: 3
    autoReplace: true

---
# Batch pool with scheduled autoscaling
apiVersion: navarch.io/v1alpha1
kind: Pool
metadata:
  name: batch
  labels:
    workload: batch
spec:
  providerRef: lambda
  instanceType: gpu_1x_a100_80gb_sxm4
  region: us-west-2
  scaling:
    minReplicas: 0
    maxReplicas: 100
    cooldownPeriod: 3m
    autoscaler:
      type: scheduled
      schedule:
        # Business hours: larger capacity
        - daysOfWeek: [monday, tuesday, wednesday, thursday, friday]
          startHour: 9
          endHour: 18
          minReplicas: 10
          maxReplicas: 100
        # Weekends: minimal capacity
        - daysOfWeek: [saturday, sunday]
          startHour: 0
          endHour: 24
          minReplicas: 0
          maxReplicas: 10
      fallback:
        type: reactive
        scaleUpThreshold: 80
        scaleDownThreshold: 20
  health:
    unhealthyThreshold: 2
    autoReplace: true

---
# Critical pool with composite autoscaling
apiVersion: navarch.io/v1alpha1
kind: Pool
metadata:
  name: critical
  labels:
    workload: critical
    sla: high
spec:
  providerRef: lambda
  instanceType: gpu_8x_h100_sxm5
  region: us-west-2
  scaling:
    minReplicas: 5
    maxReplicas: 30
    cooldownPeriod: 2m
    autoscaler:
      type: composite
      mode: max
      autoscalers:
        - type: reactive
          scaleUpThreshold: 70
          scaleDownThreshold: 30
        - type: queue
          jobsPerNode: 50
  health:
    unhealthyThreshold: 1
    autoReplace: true

---
# Development pool using fake provider
apiVersion: navarch.io/v1alpha1
kind: Pool
metadata:
  name: dev
  labels:
    workload: dev
    environment: development
spec:
  providerRef: fake
  instanceType: gpu_8x_h100
  region: local
  scaling:
    minReplicas: 1
    maxReplicas: 5
    cooldownPeriod: 10s
    autoscaler:
      type: reactive
      scaleUpThreshold: 80
      scaleDownThreshold: 20
  health:
    unhealthyThreshold: 2
    autoReplace: true

